--- #YAML:1.0
name:         Apache2::Ajax
version:      0.11
version_from: lib/Apache2/Ajax.pm
license:      perl
abstract:     mod_perl interface to CGI::Ajax
installdirs:  site
authored_by:
    - Randy Kobes <r.kobes@uwinnipeg.ca>
requires:
    CGI::Ajax:    0
    Apache2::RequestRec:    0
provides:
  Apache2::Ajax:
    file: lib/Apache2/Ajax.pm
    version: 0.11
distribution_type: module
no_index:
    file:
         - t/response/TestAjax/basic.pm
         - t/response/TestAjax/error_fn.pm
         - t/response/TestAjax/error_html.pm
         - t/response/TestAjax/formdump.pm
         - t/response/TestAjax/chained.pm
         - t/response/TestAjax/no_build.pm
         - t/response/TestAjax/show_js.pm
         - t/response/TestAjax/subs.pm
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
generated_by:        ExtUtils::MakeMaker version 6.3101
